---
- name: generate systemd service
  template:
    src: "{{ consul_mode }}/systemd.service.j2"
    dest: "/etc/systemd/system/consul.service"
    mode: 0640
  notify: restart consul

- name: generate rsyslog configuration
  copy:
    dest: "/etc/rsyslog.d/consul.conf"
    mode: 0640
    content: |-
      :programname, isequal, "consul" {{ consul_log_dest }}
      & stop
  notify: restart rsyslog

- name: restrain access to https interface to {{ consul_user_name }} user
  iptables:
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination_port: "{{ consul_http_port }}"
    uid_owner: "{{ consul_user_name }}"
    jump: ACCEPT
    comment: restrict local http to {{ consul_user_name }} user

- name: make consul service available
  service:
    name: "{{ consul_user_name }}"
    state: started
    enabled: yes
